modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"

[[mods]]
modId = "cityblocks"

version = "${file.jarVersion}"
displayName = "Crafting Dead Addon Blocks"

displayURL = "https://github.com/nexusnode/craftingdead_addon_blocks"
issueTrackerURL = "https://github.com/nexusnode/craftingdead_addon_blocks/issues"

authors = "hallzmine, juanmuscaria"
credits = "hallzmine, juanmuscaria"
description = '''
    Addon blocks for Crafting Dead
'''

[[dependencies.cityblocks]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cityblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"